import jsPDF from 'jspdf';

export function generatePDF(data) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const w = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(16, 120, 80);
  doc.text('Bill-y', 20, y);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text('Bill Analysis Summary', 55, y);
  y += 12;

  doc.setDrawColor(226, 232, 240);
  doc.line(20, y, w - 20, y);
  y += 10;

  // Bill Summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text(data.billType || 'Utility Bill', 20, y);
  y += 7;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`Billing Month: ${data.billingMonth || 'N/A'}`, 20, y);
  doc.text(`Due Date: ${data.dueDate || 'N/A'}`, 110, y);
  y += 7;

  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text(`Rs. ${(data.totalAmount || 0).toLocaleString()}`, 20, y);
  y += 7;

  if (data.unitsConsumed) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(`Units Consumed: ${data.unitsConsumed} ${data.unitLabel || ''}`, 20, y);
    y += 5;
  }
  if (data.comparisonText) {
    doc.text(data.comparisonText, 20, y);
    y += 5;
  }
  y += 8;

  // Charges
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('Charge Breakdown', 20, y);
  y += 8;

  if (data.charges) {
    data.charges.forEach(c => {
      if (y > 265) { doc.addPage(); y = 20; }
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(30, 41, 59);
      doc.text(c.name, 20, y);
      doc.text(`Rs. ${(c.amount || 0).toLocaleString()}`, w - 50, y);
      y += 5;
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 116, 139);
      const lines = doc.splitTextToSize(c.explanation, w - 50);
      doc.text(lines, 20, y);
      y += lines.length * 4 + 4;
    });
  }
  y += 6;

  // Recommendations
  if (data.recommendations && y < 240) {
    if (y > 250) { doc.addPage(); y = 20; }
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text('Recommendations', 20, y);
    y += 8;
    data.recommendations.forEach(r => {
      if (y > 265) { doc.addPage(); y = 20; }
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(30, 41, 59);
      doc.text(`[${r.effort}] ${r.title}`, 20, y);
      y += 5;
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 116, 139);
      const lines = doc.splitTextToSize(r.explanation, w - 50);
      doc.text(lines, 20, y);
      y += lines.length * 4 + 4;
    });
  }

  // Footer
  const pages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by Bill-y — billypk.app', 20, 290);
    doc.text(`Page ${i} of ${pages}`, w - 40, 290);
  }

  doc.save(`billy-summary-${(data.billingMonth || 'bill').replace(/\s/g, '-')}.pdf`);
}
