import jsPDF from 'jspdf';

/* ═══════ Brand Palette ═══════ */
const PAL = {
  primary: [16, 120, 80],
  dark: [15, 23, 42],
  muted: [100, 116, 139],
  light: [226, 232, 240],
  white: [255, 255, 255],
  green: [16, 185, 129],
  red: [239, 68, 68],
  amber: [245, 158, 11],
  blue: [59, 130, 246],
  slate: [148, 163, 184],
  bg: [249, 250, 251],
};

const M = 16;
const W = 210;
const H = 297;
const CW = W - M * 2; // content width

/* ═══════ Helpers ═══════ */
function header(doc, pageNum, totalPages) {
  doc.setFillColor(...PAL.primary);
  doc.rect(0, 0, W, 28, 'F');

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PAL.white);
  doc.text('Bill-y', M, 18);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(200, 230, 215);
  doc.text('Smart Bill Analyzer', M + 32, 18);

  doc.setFontSize(8);
  doc.setTextColor(...PAL.white);
  doc.text(`Page ${pageNum} of ${totalPages}`, W - M, 18, { align: 'right' });
}

function footer(doc) {
  doc.setFillColor(...PAL.bg);
  doc.rect(0, H - 10, W, 10, 'F');
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...PAL.slate);
  doc.text('Generated by Bill-y  \u2022  billypk.app', M, H - 4);
}

function sectionTitle(doc, y, title) {
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PAL.dark);
  doc.text(title, M, y);
  doc.setDrawColor(...PAL.primary);
  doc.setLineWidth(0.5);
  doc.line(M, y + 3, M + 40, y + 3);
  return y + 14;
}

function statCard(doc, x, y, w, label, value, sub) {
  doc.setFillColor(...PAL.bg);
  doc.roundedRect(x, y, w, 30, 2, 2, 'F');

  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...PAL.slate);
  doc.text(label.toUpperCase(), x + 6, y + 10);

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PAL.dark);
  doc.text(value, x + 6, y + 23);

  if (sub) {
    doc.setFontSize(7);
    doc.setTextColor(...PAL.green);
    doc.text(sub, x + 6, y + 28);
  }
}

/* ═══════ Native Pie Chart ═══════ */
function drawPieChart(doc, x, y, r, data, labels) {
  const total = data.reduce((a, b) => a + b, 0);
  let angle = 0;
  const colors = [PAL.primary, PAL.blue, PAL.amber, PAL.slate, PAL.red, [120, 120, 120]];

  data.forEach((val, i) => {
    const sliceAngle = (val / total) * Math.PI * 2;
    doc.setFillColor(...(colors[i % colors.length]));
    doc.setDrawColor(...PAL.white);
    doc.setLineWidth(1.5);

    // Draw pie slice as a filled polygon
    const steps = 30;
    const pts = [];
    for (let s = 0; s <= steps; s++) {
      const a = angle + (sliceAngle * s) / steps;
      pts.push({
        x: x + Math.cos(a - Math.PI / 2) * r,
        y: y + Math.sin(a - Math.PI / 2) * r,
      });
    }
    // Build path string for pdf
    let d = `M ${x} ${y}`;
    pts.forEach((p) => { d += ` L ${p.x} ${p.y}`; });
    d += ' Z';
    doc.path(d, 'FD');

    angle += sliceAngle;
  });

  // White inner circle for donut effect
  doc.setFillColor(...PAL.white);
  doc.setDrawColor(...PAL.white);
  doc.circle(x, y, r * 0.55, 'FD');

  // Center label
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PAL.dark);
  doc.text('Charges', x, y - 2, { align: 'center' });
  doc.setFontSize(14);
  doc.text(`Rs. ${total.toLocaleString()}`, x, y + 5, { align: 'center' });

  // Legend on the right
  let ly = y - r + 4;
  labels.forEach((label, i) => {
    const c = colors[i % colors.length];
    doc.setFillColor(...c);
    doc.circle(x + r + 12, ly, 1.8, 'F');
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...PAL.dark);
    doc.text(label.name, x + r + 18, ly + 1);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...PAL.slate);
    doc.text(`Rs. ${label.amount.toLocaleString()}`, x + r + 18, ly + 5);
    ly += 14;
  });
}

/* ═══════ Native Bar Chart ═══════ */
function drawBarChart(doc, x, y, w, h, data, labelKey, valueKey, unit) {
  const barW = (w - 20) / data.length;
  const maxVal = Math.max(...data.map((d) => d[valueKey]));
  const chartH = h - 22;

  // Axis lines
  doc.setDrawColor(...PAL.light);
  doc.setLineWidth(0.3);
  doc.line(x, y + chartH, x + w, y + chartH);

  data.forEach((d, i) => {
    const val = d[valueKey] || 0;
    const barH = maxVal ? (val / maxVal) * (chartH - 8) : 0;
    const bx = x + 10 + i * barW + barW * 0.2;
    const bw = barW * 0.6;

    // Bar
    doc.setFillColor(...PAL.primary);
    doc.roundedRect(bx, y + chartH - barH, bw, barH, 2, 2, 'F');

    // Value label
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...PAL.dark);
    doc.text(`Rs. ${val.toLocaleString()}`, bx + bw / 2, y + chartH - barH - 3, { align: 'center' });

    // X label
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...PAL.slate);
    doc.text(d[labelKey], bx + bw / 2, y + chartH + 7, { align: 'center' });
  });

  // Y-axis label
  doc.setFontSize(7);
  doc.setTextColor(...PAL.slate);
  doc.text(unit || '', x - 4, y + 5, { align: 'right' });
}

function fmtCompact(n) {
  if (n >= 100000) return (n / 1000).toFixed(0) + 'K';
  if (n >= 1000) return (n / 1000).toFixed(1) + 'K';
  return n.toLocaleString();
}

/* ═══════ Native Line Chart ═══════ */
function drawLineChart(doc, x, y, w, h, data, xKey, yKey, unit) {
  const padding = 22;
  const chartW = w - padding * 2;
  const chartH = h - padding * 2;
  const values = data.map((d) => d[yKey]);
  const minVal = Math.min(...values);
  const maxVal = Math.max(...values);
  const range = maxVal - minVal || 1;

  // Grid lines
  doc.setDrawColor(...PAL.light);
  doc.setLineWidth(0.2);
  for (let g = 0; g <= 4; g++) {
    const gy = y + padding + (chartH * g) / 4;
    doc.line(x + padding, gy, x + padding + chartW, gy);
    const gv = Math.round(maxVal - (range * g) / 4);
    doc.setFontSize(6);
    doc.setTextColor(...PAL.slate);
    doc.text(fmtCompact(gv), x + padding - 3, gy + 1.5, { align: 'right' });
  }

  // Area fill
  const pts = data.map((d, i) => {
    const px = x + padding + (chartW * i) / (data.length - 1 || 1);
    const py = y + padding + chartH - ((d[yKey] - minVal) / range) * chartH;
    return { x: px, y: py };
  });

  let areaPath = `M ${pts[0].x} ${y + padding + chartH}`;
  pts.forEach((p) => { areaPath += ` L ${p.x} ${p.y}`; });
  areaPath += ` L ${pts[pts.length - 1].x} ${y + padding + chartH} Z`;
  doc.setFillColor(230, 245, 238);
  doc.path(areaPath, 'F');

  // Line
  doc.setDrawColor(...PAL.primary);
  doc.setLineWidth(1.2);
  let linePath = `M ${pts[0].x} ${pts[0].y}`;
  pts.forEach((p) => { linePath += ` L ${p.x} ${p.y}`; });
  doc.path(linePath, 'S');

  // Dots
  pts.forEach((p, i) => {
    doc.setFillColor(...PAL.primary);
    doc.circle(p.x, p.y, 1.8, 'F');
    doc.setFillColor(...PAL.white);
    doc.circle(p.x, p.y, 0.8, 'F');

    // X label
    doc.setFontSize(6);
    doc.setTextColor(...PAL.slate);
    doc.text(data[i][xKey], p.x, y + padding + chartH + 8, { align: 'center' });
  });
}

/* ═══════ Savings Bar ═══════ */
function drawSavingsBar(doc, x, y, w, amount, max) {
  const barH = 10;
  const pct = Math.min((amount / max) * 100, 100);

  doc.setFillColor(...PAL.light);
  doc.roundedRect(x, y, w, barH, 3, 3, 'F');

  doc.setFillColor(...PAL.green);
  doc.roundedRect(x, y, (w * pct) / 100, barH, 3, 3, 'F');

  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PAL.dark);
  doc.text(`Potential monthly savings: Rs. ${amount.toLocaleString()}`, x, y - 4);
}

/* ═══════ Recommendation Card ═══════ */
function drawRecCard(doc, x, y, w, rec) {
  const effortColors = { EASY: PAL.green, MEDIUM: PAL.amber, HIGH: PAL.red };
  const color = effortColors[rec.effort] || PAL.slate;

  doc.setFillColor(...PAL.bg);
  doc.roundedRect(x, y, w, 32, 2, 2, 'F');

  // Effort badge
  doc.setFillColor(...color);
  doc.roundedRect(x + 6, y + 5, 26, 9, 1.5, 1.5, 'F');
  doc.setFontSize(6);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PAL.white);
  doc.text(rec.effort, x + 6 + 13, y + 11, { align: 'center' });

  // Title
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PAL.dark);
  doc.text(rec.title, x + 36, y + 12);

  // Explanation
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...PAL.muted);
  const lines = doc.splitTextToSize(rec.explanation, w - 42);
  doc.text(lines, x + 36, y + 17);

  // Savings
  if (rec.savings && rec.savings !== 'Penalty avoidance') {
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...PAL.green);
    doc.text(`Save ${rec.savings}`, x + 36, y + 17 + lines.length * 3 + 2);
  }

  return y + 32 + 4;
}

/* ═══════ Main Export ═══════ */
export async function generatePDF(data) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });

  // We'll build all pages then know total count for headers
  // First pass: draw everything into temp arrays, count pages
  // Simpler: just draw sequentially and add headers after

  let page = 1;
  let y = 36;

  // ═══ PAGE 1 ═══
  // Bill Type & Month
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...PAL.slate);
  doc.text(data.billingMonth || '', M, y);
  y += 6;

  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PAL.dark);
  doc.text(data.billType || 'Utility Bill', M, y);
  y += 10;

  // Big amount
  doc.setFontSize(36);
  doc.setTextColor(...PAL.primary);
  doc.text(`Rs. ${(data.totalAmount || 0).toLocaleString()}`, M, y);
  y += 8;

  if (data.comparisonText) {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...PAL.green);
    doc.text(data.comparisonText, M, y);
    y += 4;
  }

  doc.setFontSize(8);
  doc.setTextColor(...PAL.slate);
  doc.text(`Due: ${data.dueDate || 'N/A'}  \u2022  Issue: ${data.issueDate || 'N/A'}${data.isPastDue ? '  \u2022  PAST DUE' : ''}`, M, y);
  y += 16;

  // KPI row
  const kw = (CW - 16) / 3;
  statCard(doc, M, y, kw, 'Units Consumed', `${(data.unitsConsumed || 0).toLocaleString()} ${data.unitLabel || 'kWh'}`);
  statCard(doc, M + kw + 8, y, kw, 'Net Position', data.isNetMetering && data.netMetering ? `${data.netMetering.netPosition} kWh` : '\u2014');
  statCard(doc, M + 2 * (kw + 8), y, kw, 'AI Confidence', data.confidenceScore ? `${data.confidenceScore}%` : '\u2014');
  y += 42;

  // Charge Breakdown
  y = sectionTitle(doc, y, 'Charge Breakdown');

  if (data.charges && data.charges.length) {
    const chartY = y;
    const chartR = 28;
    const amounts = data.charges.map((c) => c.amount || 0);
    drawPieChart(doc, M + chartR, chartY + chartR, chartR, amounts, data.charges);

    // Charge explanations below chart
    y = chartY + chartR * 2 + 8;
    data.charges.forEach((c, i) => {
      if (y > 265) { doc.addPage(); y = 36; page++; }

      const statusColor = {
        NORMAL: PAL.green, FIXED: PAL.slate, GOVERNMENT: PAL.blue, OVERDUE: PAL.red, WARNING: PAL.amber,
      }[c.status] || PAL.slate;

      doc.setFillColor(...statusColor);
      doc.circle(M + 2, y + 2, 1.8, 'F');

      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...PAL.dark);
      doc.text(`${c.name}`, M + 8, y + 3);

      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...PAL.slate);
      doc.text(`Rs. ${(c.amount || 0).toLocaleString()}`, W - M, y + 3, { align: 'right' });
      y += 5;

      doc.setFontSize(7.5);
      const lines = doc.splitTextToSize(c.explanation, CW - 10);
      doc.text(lines, M + 8, y);
      y += lines.length * 3.5 + 5;
    });
  }

  // ═══ Consumption & Solar ═══
  if (y > 200) { doc.addPage(); page++; y = 36; }

  y = sectionTitle(doc, y, 'Consumption Trend');
  if (data.consumptionHistory && data.consumptionHistory.length > 1) {
    drawLineChart(doc, M, y, CW, 55, data.consumptionHistory.slice(-12), 'month', 'amount', 'Rs.');
    y += 62;
  }

  y = sectionTitle(doc, y, 'Recent Bills Comparison');
  if (data.recentBills && data.recentBills.length) {
    drawBarChart(doc, M, y, CW, 50, data.recentBills, 'month', 'amount', 'Rs.');
    y += 58;
  }

  // Solar
  if (data.isNetMetering && data.netMetering) {
    y = sectionTitle(doc, y, 'Solar & Net Metering');
    const nm = data.netMetering;
    const sw = (CW - 16) / 3;
    statCard(doc, M, y, sw, 'Imported', `${nm.unitsImported} kWh`);
    statCard(doc, M + sw + 8, y, sw, 'Exported', `${nm.unitsExported} kWh`, 'Net exporter');
    statCard(doc, M + 2 * (sw + 8), y, sw, 'Net Position', `${nm.netPosition} kWh`);
    y += 40;

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...PAL.slate);
    doc.text(`Peak: ${nm.importPeak} kWh  |  Off-Peak: ${nm.importOffPeak} kWh  |  DG: ${nm.dgCapacity} kW  |  MDI: ${nm.expMdi} kW`, M, y);
    y += 8;

    if (data.solarInsights && data.solarInsights.length) {
      data.solarInsights.forEach((si) => {
        const prefix = si.type === 'tip' ? '[TIP]' : si.type === 'warning' ? '[WARN]' : '[INFO]';
        doc.setFontSize(8);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...PAL.dark);
        doc.text(`${prefix}  ${si.title}`, M, y);
        y += 4;
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...PAL.muted);
        const lines = doc.splitTextToSize(si.body, CW - 8);
        doc.text(lines, M + 10, y);
        y += lines.length * 3.5 + 3;
      });
    }
  }

  // Change Reasons
  if (data.changeReasons && data.changeReasons.length) {
    if (y > 240) { doc.addPage(); y = 36; page++; }
    y = sectionTitle(doc, y, 'What Changed This Month');
    data.changeReasons.forEach((cr) => {
      if (y > 260) { doc.addPage(); y = 36; page++; }
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...PAL.dark);
      doc.text(`${cr.title}`, M, y);
      y += 4;
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...PAL.muted);
      const lines = doc.splitTextToSize(cr.explanation, CW - 8);
      doc.text(lines, M + 10, y);
      y += lines.length * 3.5 + 3;
    });
  }

  // ═══ Recommendations ═══
  if (y > 200) { doc.addPage(); page++; y = 36; }

  y = sectionTitle(doc, y, 'Recommendations');
  if (data.estimatedSavings) {
    drawSavingsBar(doc, M, y, CW, data.estimatedSavings, data.estimatedSavings * 1.5);
    y += 22;
  }

  if (data.recommendations && data.recommendations.length) {
    data.recommendations.forEach((r) => {
      if (y > 250) { doc.addPage(); y = 36; page++; }
      y = drawRecCard(doc, M, y, CW, r);
    });
  }

  // ═══ Final pass: add headers & footers ═══
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    header(doc, i, totalPages);
    footer(doc);
  }

  const filename = `Bill-y-Report-${(data.billingMonth || 'bill').replace(/\s/g, '-')}.pdf`;
  doc.save(filename);
}
